# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  deno-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno fmt --check
      - run: deno lint

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.x'
      - run: go vet ./...
      - run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
