name: PR

env:
 DENO_VERSION: ^v2.9

on:
 pull_request:
  types:
   - opened
   - synchronize
   - ready_for_review
 workflow_dispatch:

jobs:
 changes:
  name: Detect changes
  runs-on: ubuntu-latest
  outputs:
   go: ${{ steps.filter.outputs.go }}
   sql: ${{ steps.filter.outputs.sql }}
   deno_code: ${{ steps.filter.outputs.deno_code }}
   frontend: ${{ steps.filter.outputs.frontend }}
   markdown: ${{ steps.filter.outputs.markdown }}
  steps:
   - uses: actions/checkout@v6
   - uses: dorny/paths-filter@v3
     id: filter
     with:
      filters: |
       go:
        - '**/*.go'
        - 'go.mod'
        - 'go.sum'
        - 'go.work'
        - 'server/**'
       sql:
        - '**/*.sql'
       deno_code:
        - '**/*.?([cm])[jt]s'
        - '**/*.[jt]sx'
        - 'deno.json'
        - 'deno.jsonc'
        - 'deno.lock'
       frontend:
        - '**/*.css'
        - '**/*.svg'
        - '**/*.html'
        - '**/*.tmpl'
        - 'client/src/assets/swagger.yaml'
        - 'client/**'
        - 'scripts/**'
       markdown:
        - '**/*.md'

 govulncheck:
  name: Vulnerabilities
  needs: changes
  if: needs.changes.outputs.go == 'true'
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v6
     with:
      persist-credentials: false
   - uses: actions/setup-go@v6
     with:
      go-version-file: go.mod
   - run: |
      go run golang.org/x/vuln/cmd/govulncheck@latest ./...

 types-deno:
  name: Deno Types
  needs: changes
  if: github.event.pull_request.draft == false && needs.changes.outputs.deno_code == 'true'
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v6
     with:
      ref: ${{ github.head_ref }}
      token: ${{ secrets.GITHUB_TOKEN }}
      repository: ${{ github.repository }}
   - uses: denoland/setup-deno@v2
     with:
      deno-version: ${{ env.DENO_VERSION }}
      cache: true
   - run: deno check

 lint-deno:
  name: Deno Lint
  needs: changes
  if: github.event.pull_request.draft == false && needs.changes.outputs.deno_code == 'true'
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v6
     with:
      ref: ${{ github.head_ref }}
      token: ${{ secrets.GITHUB_TOKEN }}
      repository: ${{ github.repository }}
   - uses: denoland/setup-deno@v2
     with:
      deno-version: ${{ env.DENO_VERSION }}
      cache: true
   - run: deno lint

 fmt-deno:
  name: Deno Format
  needs: changes
  if: |
   github.event.pull_request.draft == false &&
   (needs.changes.outputs.deno_code == 'true' ||
    needs.changes.outputs.frontend == 'true' ||
    needs.changes.outputs.markdown == 'true')
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v6
     with:
      ref: ${{ github.head_ref }}
      token: ${{ secrets.GITHUB_TOKEN }}
      repository: ${{ github.repository }}
   - uses: denoland/setup-deno@v2
     with:
      deno-version: ${{ env.DENO_VERSION }}
      cache: true
   - run: deno fmt --check

 fmt-go:
  name: Go Format
  needs: changes
  if: github.event.pull_request.draft == false && needs.changes.outputs.go == 'true'
  env:
   GOCACHE: ${{ github.workspace }}/dist/cache
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v6
     with:
      ref: ${{ github.head_ref }}
      token: ${{ secrets.GITHUB_TOKEN }}
      repository: ${{ github.repository }}
   - uses: actions/setup-go@v6
     with:
      go-version-file: go.mod
   - run: go fmt ./...
   - name: git diff
     run: git diff; git diff --quiet

 mod-go:
  name: Go Mod
  needs: changes
  if: github.event.pull_request.draft == false && needs.changes.outputs.go == 'true'
  env:
   GOCACHE: ${{ github.workspace }}/dist/cache
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v6
     with:
      ref: ${{ github.head_ref }}
      token: ${{ secrets.GITHUB_TOKEN }}
      repository: ${{ github.repository }}
   - uses: actions/setup-go@v6
     with:
      go-version-file: go.mod
   - run: go mod tidy
   - name: git diff
     run: git diff; git diff --quiet

 test-deno:
  name: Deno Test
  needs: changes
  if: github.event.pull_request.draft == false && needs.changes.outputs.deno_code == 'true'
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v6
     with:
      ref: ${{ github.head_ref }}
      token: ${{ secrets.GITHUB_TOKEN }}
      repository: ${{ github.repository }}
   - uses: denoland/setup-deno@v2
     with:
      deno-version: ${{ env.DENO_VERSION }}
      cache: true
   - run: deno test --permit-no-files

 test-go:
  name: Go Test
  needs: changes
  if: |
   github.event.pull_request.draft == false &&
   (needs.changes.outputs.go == 'true' ||
    needs.changes.outputs.sql == 'true' ||
    needs.changes.outputs.deno_code == 'true' ||
    needs.changes.outputs.frontend == 'true')
  env:
   GOCACHE: ${{ github.workspace }}/dist/cache
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v6
     with:
      ref: ${{ github.head_ref }}
      token: ${{ secrets.GITHUB_TOKEN }}
      repository: ${{ github.repository }}
   - uses: actions/setup-go@v6
     with:
      go-version-file: go.mod
   - uses: denoland/setup-deno@v2
     with:
      deno-version: ${{ env.DENO_VERSION }}
      cache: true
   - run: deno install
   - run: deno task front
   - run: go generate ./...
   - run: go test ./...

 build:
  name: Build
  needs:
   - changes
   - govulncheck
   - types-deno
   - lint-deno
   - fmt-deno
   - fmt-go
   - mod-go
   - test-deno
   - test-go
  if: |
   github.event.pull_request.draft == false &&
   (needs.changes.outputs.go == 'true' ||
    needs.changes.outputs.sql == 'true' ||
    needs.changes.outputs.deno_code == 'true' ||
    needs.changes.outputs.frontend == 'true')
  env:
   GOCACHE: ${{ github.workspace }}/dist/cache
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v6
     with:
      ref: ${{ github.head_ref }}
      token: ${{ secrets.GITHUB_TOKEN }}
      repository: ${{ github.repository }}
   - uses: denoland/setup-deno@v2
     with:
      deno-version: ${{ env.DENO_VERSION }}
      cache: true
   - run: deno install
   - run: deno task front
   - uses: actions/setup-go@v6
     with:
      go-version-file: go.mod
   - run: deno task back:cross
   - run: deno task back:cross dev
   - name: Upload server binaries
     uses: nanoufo/action-upload-artifacts-and-release-assets@v2
     with:
      path: |
       dist/server-*
